### ISSUE TITLE
Add Simplified Ticket Entity Grid Item

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-recurring-events-manager#12]
In REM, we need to display the list of tickets that have been added to the date being used to set up the recurrence, but the existing `EditorTicketEntityGridItem` may be overkill and complicate things more than they need to be. A simplified version of this component may provide a better UX

**Comment by tn3rb** [comment]
here's a simple mockup that's open for modification as needs change

![ScreenShot_20200713101109](https://user-images.githubusercontent.com/1751030/87333077-73f7bf00-c4f1-11ea-838b-f85ad17cab3a.png)

and here's the css I used:

```css
.ticket-list {
    display: flex;
    justify-content: flex-start;
}

.ticket {
    display: flex;
    border: 1px solid #ccc;
    margin: .5rem 1rem;
    color: #000;
}

.ticket__price {
    color: #999;
    font-weight: 700;
    padding: .25rem;
    writing-mode: vertical-lr;
    text-align: center;
    width: 1.5rem;
    font-size: .7rem;
    letter-spacing: 2px;
    transform: rotate(180deg);
}

.ticket__details {
    flex-flow: column;
    padding: .5rem .75rem .5rem;
    border-left: 1px dotted #ccc;
    width: 13rem;
    height: 6rem;
    display: flex;
    justify-content: space-between;
    line-height: 1rem;
    font-size: .6rem;
}

.ticket__name {
    font-size: 1rem;
    height: 3rem;
    font-weight: 700;
    color: #555;
}

.date-offset__start, .date-offset__end {
    letter-spacing: 1px;
}

.date-offset__start span, .date-offset__end span {
    color: #787878;
}
```

which is just from my dev tools and isn't using sass nor ee css vars
